---
title: "data_cleaning"
author: "Cande Torres"
date: "11/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyr)
library(readr)
library(ggplot2)
library(dplyr)
library(broom)
```

```{r}
library(readxl)
IV <- read_excel("Index_IV_Data_collection.xlsx",col_types = c("text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))
```

```{r}
table(IV$`Talent Competitiveness Ranking (IMD)`)
```

```{r}
IV_ranked<-IV %>% 
  mutate(across(c(`PISA Math (2018)`,`PISA Science (2018)`,`PISA Reading (2018)`,`Quality of Education System (CEOWORLD)`, `Opportunity [in education] (CEOWORLD)`,`Talent Competitiveness Ranking (IMD)`),
    ~min_rank(.x)))

```

```{r}
IV_indexed<- IV_ranked %>% 
  mutate(IV_index = `PISA Math (2018)`+
           `PISA Science (2018)`+
           `PISA Reading (2018)`+
           `Quality of Education System (CEOWORLD)`+
           `Opportunity [in education] (CEOWORLD)`+
           `Position (2020)`)
```

```{r}
IV_indexed<-IV_indexed %>% 
  mutate(PISA_index=`PISA Math (2018)`+
           `PISA Science (2018)`+
           `PISA Reading (2018)`)
```

```{r}
IV_indexed<-IV_indexed %>% 
  mutate(CEOWORLD_index=`Quality of Education System (CEOWORLD)`+
           `Opportunity [in education] (CEOWORLD)`)
```

```{r}
IV_1<- IV_indexed %>% 
  filter(!is.na(IV_index))
```

```{r}
IV_2<- IV_indexed %>% 
  filter(!is.na(PISA_index))
```

```{r}
IV_3<- IV_indexed %>% 
  filter(!is.na(CEOWORLD_index))
```



#Write new data set 

```{r}
library(writexl)
```

```{r}
write.csv(IV_indexed,"ADS_project_data_IV.csv")
write_xlsx(IV_indexed,"ADS_project_data_IV.xlsx")
```



