---
title: "Data_Viz_project"
author: "Cande Torres"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tidyr)
library(readr)
library(ggplot2)
library(dplyr)
library(broom)
library(readxl)
library(readr)
library(janitor)
library(lubridate)
library(stringr)
```

# TIMSS

```{r}
library(readxl)
TIMSS_S4 <- read_excel("~/Desktop/Fall21/Honors/Methods/data/TIMSS_2019_S4.xlsx", 
    col_types = c("text", "numeric", "numeric"))
TIMSS_S8 <- read_excel("~/Desktop/Fall21/Honors/Methods/data/TIMSS_2019_S8.xlsx", 
    col_types = c("text", "numeric", "numeric"))
TIMSS_M4 <- read_excel("~/Desktop/Fall21/Honors/Methods/data/TIMSS_19_M4.xlsx", 
    col_types = c("text", "numeric", "numeric"))
TIMSS_M8 <- read_excel("~/Desktop/Fall21/Honors/Methods/data/TIMSS_2019_M8.xlsx", 
    col_types = c("text", "numeric", "numeric"))
```

```{r}
TIMSS4<-left_join(TIMSS_M4,TIMSS_S4, by=c("Country"="Country"))
```
```{r}
TIMSS8<-left_join(TIMSS_M8,TIMSS_S8, by=c("Country"="Country"))
```
```{r}
TIMSS<-left_join(TIMSS8,TIMSS4, by=c("Country"="Country"))
```

```{r}
TIMSS<-clean_names(TIMSS)
```


```{r}
TIMSS_ranked<-TIMSS %>% 
  mutate(across(c(m8_avg_scale_score,m4_avg_scale_score,s8_avg_scale_score,s4_avg_scale_score),
    ~min_rank(.x)))
```

```{r}
TIMSS_score<-TIMSS_ranked %>% 
  mutate(TIMSS_score = m8_avg_scale_score+
           m4_avg_scale_score+
           s8_avg_scale_score+
           s4_avg_scale_score)
```

```{r}
TIMSS_score<-TIMSS_score %>% 
  mutate(country = str_replace(country, "England", "United Kingdom"))
```


```{r}
simple_combine<-left_join(data_dec,IV_1, by=c("unicef_country"="Country"))
```


```{r}
simple_combine_2<-left_join(data_dec,IV_2, by=c("unicef_country"="Country"))
```

```{r}
simple_combine_3<-left_join(data_dec,IV_3, by=c("unicef_country"="Country"))
```

```{r}
simp_combine_2<-clean_names(simple_combine_2)
```

```{r}
plusTIMSS<-left_join(TIMSS_score,simp_combine_2, by=c("country"="unicef_country"))
```

```{r}
plusTIMSS <-plusTIMSS %>% 
  mutate(cat_c1= as.factor(c1_school_closing))
```

```{r}
plusTIMSS<-plusTIMSS %>% 
  mutate(prop_instruction= instruction_days/365)
```
```{r}
plusTIMSS<-plusTIMSS %>% 
  mutate(prop_closed= days_fully_closed/365)
```



# random exporations

Don't worry if it doesn't run, I was just playing with the data

```{r}
lm(c_new_dv_index~pisa_index+
     ceoworld_index+
     talent_competitiveness_ranking_imd+ 
     TIMSS_score+
     best_countries_for_education_ranking_us_news_2020+ 
     #c1_school_closing+ economic_support_index+ 
     cat_c1+
     confirmed_cases+
     confirmed_deaths+
     government_response_index+
     stringency_index+
     economic_support_index, 
   data=plusTIMSS) %>% 
  summary()
```
```{r}
lm(b_new_dv_index~pisa_index+
     ceoworld_index+
     talent_competitiveness_ranking_imd+ 
     TIMSS_score+
     best_countries_for_education_ranking_us_news_2020+ 
     #c1_school_closing+ economic_support_index+ 
     #cat_c1+
     confirmed_cases+
     confirmed_deaths+
     government_response_index+
     stringency_index+
     economic_support_index, 
   data=plusTIMSS) %>% 
  summary()
```
```{r}
lm(prop_closed~pisa_index+
     ceoworld_index+
     talent_competitiveness_ranking_imd+ 
     TIMSS_score+
     best_countries_for_education_ranking_us_news_2020+ 
     #c1_school_closing+ economic_support_index+ 
    # cat_c1+
     confirmed_cases+
     confirmed_deaths+
     government_response_index+
     stringency_index+
     economic_support_index, 
   data=plusTIMSS) %>% 
  summary()
```
```{r}
plusTIMSS%>% 
  ggplot(aes(x=pisa_index, y=days_fully_closed))+
  geom_point()+
  geom_smooth(method=lm)
  
```





```{r}
plusTIMSS%>% 
  ggplot(aes(x=pisa_index, y=c_new_dv_index))+
  geom_point()+
  geom_smooth(method=lm)
  
```
```{r}
plusTIMSS%>% 
  ggplot(aes(x=TIMSS_score, y=c_new_dv_index))+
  geom_point()+
  geom_smooth(method=lm)
  
```


```{r}
data_dec<- data_join %>% 
  filter(date ==20201215)
```

```{r}
data_dec <- data_dec %>% 
  mutate(prop_instruction= instruction_days/365) %>% 
  mutate(prop_closed= days_fully_closed/365)
```


```{r}
plusTIMSS2<-left_join(TIMSS_score,data_dec, by=c("country"="unicef_country"))
```







